# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: strategicblue/cljs-builder:latest

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: npm i 

      - save_cache:
          paths:
            - ~/node_modules
    
      - run: npm t 
    
      - save_cache:
          paths:
            - ~/.m2

workflows:
  build:
    jobs:
      - build
